image: python:3.8
pipelines:
  branches:
    master: &shared
      - step:
          name: upload library to jfrog
          script:
            - git submodule update --init --recursive
            - apt update && apt -y install cmake
            - printf "[distutils]\n" >> ~/.pypirc
            - printf "index-servers=splightlib\n" >> ~/.pypirc
            - printf "[splightlib]\n" >> ~/.pypirc
            - printf "repository:https://splight.jfrog.io/artifactory/api/pypi/splight-local\n" >> ~/.pypirc
            - printf "username=bot@splight-ae.com\n" >> ~/.pypirc
            - printf "password=N0us4rExcl4maci0n" >> ~/.pypirc
            - python setup.py bdist_wheel upload -r splightlib
            - rm ~/.pypirc;
    main: *shared
